### ISSUE TITLE
How to load a lua module?

### ISSUE THREAD

**Issue by xiayudeshijie** [RyouZhang/go-lua#2]
Such as:
a.lua:
man={}
function man.eat()
{
print("eat")
}

Then I want use man.eat in Go,what should I do?

**Comment by RyouZhang** [comment]
good question, you can replace Lua require method, then in go code load Lua file into _G
But in fact, I don't suggest using Lua module, extent go module is fast and more powerful

**Comment by RyouZhang** [comment]
I think you can use the global option to load all your Lua module, then script _G['your_module_name'].eat() maybe work
