### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by mgholam** [RyouZhang/go-lua#6]
Hi, can you supply scripts to build this repo?

**Comment by kokizzu** [comment]
from `extern.go` there's seems he's using local build not one that from ubuntu-like directory (`-I` for include, `-L` for lib/static object), so you'll need to do something like this to match those directory:

```
sudo apt install -y libluajit-5.1-dev libluajit-5.1-2 libluajit-5.1-common
sudo ln -sf /usr/include/luajit-2.1 /usr/local/include/luajit-2.1
sudo ln -sf /usr/lib/x86_64-linux-gnu/libluajit-5.1.so /usr/local/lib/libluajit.so
```

after those steps, you should able to compile properly the example on readme:
```
go run a.go                                                                       
cost: 71.520613ms
9227465 <nil>
```
